# $LOAD_PATH handling not need if the standalone_migrations
# gem is installed
lib = File.expand_path("../vendor/standalone-migrations/lib", __FILE__)
$:.unshift lib unless $:.include?(lib)

require "standalone_migrations"
require "zlib"
require "vault"

StandaloneMigrations::Configurator.environments_config do |env|
  env.on "customized" do |customized|
    if (ENV['VAULT_ADDR'] && ENV['VAULT_TOKEN'])
      puts "Get db config from vault"
      db = Vault.logical.read("secret/indexer-db-credentials").data
      {
        "adapter"  => customized["adapter"],
        "encoding" => customized["encoding"],
        "database" => customized["database"],
        "host"     => db[:"indexer.db.cred.host"],
        "port"     => db[:"indexer.db.cred.port"],
        "username" => db[:"indexer.db.cred.user"],
        "password" => db[:"indexer.db.cred.password"]
      }
    else
      nil
    end
  end
end

StandaloneMigrations::Tasks.load_tasks

# and that's it!
