// Code generated by mockery v1.0.0
package mocks

import big "math/big"

import common "github.com/ethereum/go-ethereum/common"
import context "context"
import mock "github.com/stretchr/testify/mock"

// Balancer is an autogenerated mock type for the Balancer type
type Balancer struct {
	mock.Mock
}

// BalanceOf provides a mock function with given fields: _a0, _a1, _a2
func (_m *Balancer) BalanceOf(_a0 context.Context, _a1 *big.Int, _a2 map[common.Address]map[common.Address]struct{}) (map[common.Address]map[common.Address]*big.Int, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 map[common.Address]map[common.Address]*big.Int
	if rf, ok := ret.Get(0).(func(context.Context, *big.Int, map[common.Address]map[common.Address]struct{}) map[common.Address]map[common.Address]*big.Int); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[common.Address]map[common.Address]*big.Int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *big.Int, map[common.Address]map[common.Address]struct{}) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
