// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/maichain/eth-indexer/indexer/pb/block_header.proto

/*
	Package pb is a generated protocol buffer package.

	It is generated from these files:
		github.com/maichain/eth-indexer/indexer/pb/block_header.proto
		github.com/maichain/eth-indexer/indexer/pb/transaction.proto

	It has these top-level messages:
		BlockHeader
		Transaction
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockHeader struct {
	ID          uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"id,omitempty" gorm:"primary_key" deepequal:"-"`
	ParentHash  string `protobuf:"bytes,2,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty" gorm:"column:parent_hash;size:255"`
	UncleHash   string `protobuf:"bytes,3,opt,name=uncle_hash,json=uncleHash,proto3" json:"uncle_hash,omitempty" gorm:"column:uncle_hash;size:255"`
	Coinbase    string `protobuf:"bytes,4,opt,name=coinbase,proto3" json:"coinbase,omitempty" gorm:"column:coinbase;size:255"`
	Root        string `protobuf:"bytes,5,opt,name=root,proto3" json:"root,omitempty" gorm:"column:root;size:255"`
	TxHash      string `protobuf:"bytes,6,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty" gorm:"column:tx_hash;size:255"`
	ReceiptHash string `protobuf:"bytes,7,opt,name=receipt_hash,json=receiptHash,proto3" json:"receipt_hash,omitempty" gorm:"column:receipt_hash;size:255"`
	Bloom       []byte `protobuf:"bytes,8,opt,name=bloom,proto3" json:"bloom,omitempty" gorm:"column:bloom"`
	Difficulty  int64  `protobuf:"varint,9,opt,name=difficulty,proto3" json:"difficulty,omitempty" gorm:"column:difficulty"`
	Number      int64  `protobuf:"varint,10,opt,name=number,proto3" json:"number,omitempty" gorm:"column:number"`
	GasLimit    uint64 `protobuf:"varint,11,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty" gorm:"column:gas_limit"`
	GasUsed     uint64 `protobuf:"varint,12,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty" gorm:"column:gas_used"`
	Time        uint64 `protobuf:"varint,13,opt,name=time,proto3" json:"time,omitempty" gorm:"column:time"`
	ExtraData   []byte `protobuf:"bytes,14,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty" gorm:"column:extra_data"`
	MixDigest   string `protobuf:"bytes,15,opt,name=mix_digest,json=mixDigest,proto3" json:"mix_digest,omitempty" gorm:"column:mix_digest"`
	Nonce       uint64 `protobuf:"varint,16,opt,name=nonce,proto3" json:"nonce,omitempty" gorm:"column:nonce"`
}

func (m *BlockHeader) Reset()                    { *m = BlockHeader{} }
func (*BlockHeader) ProtoMessage()               {}
func (*BlockHeader) Descriptor() ([]byte, []int) { return fileDescriptorBlockHeader, []int{0} }

func init() {
	proto.RegisterType((*BlockHeader)(nil), "pb.BlockHeader")
}
func (m *BlockHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlockHeader) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintBlockHeader(dAtA, i, uint64(m.ID))
	}
	if len(m.ParentHash) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintBlockHeader(dAtA, i, uint64(len(m.ParentHash)))
		i += copy(dAtA[i:], m.ParentHash)
	}
	if len(m.UncleHash) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintBlockHeader(dAtA, i, uint64(len(m.UncleHash)))
		i += copy(dAtA[i:], m.UncleHash)
	}
	if len(m.Coinbase) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintBlockHeader(dAtA, i, uint64(len(m.Coinbase)))
		i += copy(dAtA[i:], m.Coinbase)
	}
	if len(m.Root) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintBlockHeader(dAtA, i, uint64(len(m.Root)))
		i += copy(dAtA[i:], m.Root)
	}
	if len(m.TxHash) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintBlockHeader(dAtA, i, uint64(len(m.TxHash)))
		i += copy(dAtA[i:], m.TxHash)
	}
	if len(m.ReceiptHash) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintBlockHeader(dAtA, i, uint64(len(m.ReceiptHash)))
		i += copy(dAtA[i:], m.ReceiptHash)
	}
	if len(m.Bloom) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintBlockHeader(dAtA, i, uint64(len(m.Bloom)))
		i += copy(dAtA[i:], m.Bloom)
	}
	if m.Difficulty != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintBlockHeader(dAtA, i, uint64(m.Difficulty))
	}
	if m.Number != 0 {
		dAtA[i] = 0x50
		i++
		i = encodeVarintBlockHeader(dAtA, i, uint64(m.Number))
	}
	if m.GasLimit != 0 {
		dAtA[i] = 0x58
		i++
		i = encodeVarintBlockHeader(dAtA, i, uint64(m.GasLimit))
	}
	if m.GasUsed != 0 {
		dAtA[i] = 0x60
		i++
		i = encodeVarintBlockHeader(dAtA, i, uint64(m.GasUsed))
	}
	if m.Time != 0 {
		dAtA[i] = 0x68
		i++
		i = encodeVarintBlockHeader(dAtA, i, uint64(m.Time))
	}
	if len(m.ExtraData) > 0 {
		dAtA[i] = 0x72
		i++
		i = encodeVarintBlockHeader(dAtA, i, uint64(len(m.ExtraData)))
		i += copy(dAtA[i:], m.ExtraData)
	}
	if len(m.MixDigest) > 0 {
		dAtA[i] = 0x7a
		i++
		i = encodeVarintBlockHeader(dAtA, i, uint64(len(m.MixDigest)))
		i += copy(dAtA[i:], m.MixDigest)
	}
	if m.Nonce != 0 {
		dAtA[i] = 0x80
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintBlockHeader(dAtA, i, uint64(m.Nonce))
	}
	return i, nil
}

func encodeVarintBlockHeader(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *BlockHeader) Size() (n int) {
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovBlockHeader(uint64(m.ID))
	}
	l = len(m.ParentHash)
	if l > 0 {
		n += 1 + l + sovBlockHeader(uint64(l))
	}
	l = len(m.UncleHash)
	if l > 0 {
		n += 1 + l + sovBlockHeader(uint64(l))
	}
	l = len(m.Coinbase)
	if l > 0 {
		n += 1 + l + sovBlockHeader(uint64(l))
	}
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovBlockHeader(uint64(l))
	}
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovBlockHeader(uint64(l))
	}
	l = len(m.ReceiptHash)
	if l > 0 {
		n += 1 + l + sovBlockHeader(uint64(l))
	}
	l = len(m.Bloom)
	if l > 0 {
		n += 1 + l + sovBlockHeader(uint64(l))
	}
	if m.Difficulty != 0 {
		n += 1 + sovBlockHeader(uint64(m.Difficulty))
	}
	if m.Number != 0 {
		n += 1 + sovBlockHeader(uint64(m.Number))
	}
	if m.GasLimit != 0 {
		n += 1 + sovBlockHeader(uint64(m.GasLimit))
	}
	if m.GasUsed != 0 {
		n += 1 + sovBlockHeader(uint64(m.GasUsed))
	}
	if m.Time != 0 {
		n += 1 + sovBlockHeader(uint64(m.Time))
	}
	l = len(m.ExtraData)
	if l > 0 {
		n += 1 + l + sovBlockHeader(uint64(l))
	}
	l = len(m.MixDigest)
	if l > 0 {
		n += 1 + l + sovBlockHeader(uint64(l))
	}
	if m.Nonce != 0 {
		n += 2 + sovBlockHeader(uint64(m.Nonce))
	}
	return n
}

func sovBlockHeader(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozBlockHeader(x uint64) (n int) {
	return sovBlockHeader(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *BlockHeader) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&BlockHeader{`,
		`ID:` + fmt.Sprintf("%v", this.ID) + `,`,
		`ParentHash:` + fmt.Sprintf("%v", this.ParentHash) + `,`,
		`UncleHash:` + fmt.Sprintf("%v", this.UncleHash) + `,`,
		`Coinbase:` + fmt.Sprintf("%v", this.Coinbase) + `,`,
		`Root:` + fmt.Sprintf("%v", this.Root) + `,`,
		`TxHash:` + fmt.Sprintf("%v", this.TxHash) + `,`,
		`ReceiptHash:` + fmt.Sprintf("%v", this.ReceiptHash) + `,`,
		`Bloom:` + fmt.Sprintf("%v", this.Bloom) + `,`,
		`Difficulty:` + fmt.Sprintf("%v", this.Difficulty) + `,`,
		`Number:` + fmt.Sprintf("%v", this.Number) + `,`,
		`GasLimit:` + fmt.Sprintf("%v", this.GasLimit) + `,`,
		`GasUsed:` + fmt.Sprintf("%v", this.GasUsed) + `,`,
		`Time:` + fmt.Sprintf("%v", this.Time) + `,`,
		`ExtraData:` + fmt.Sprintf("%v", this.ExtraData) + `,`,
		`MixDigest:` + fmt.Sprintf("%v", this.MixDigest) + `,`,
		`Nonce:` + fmt.Sprintf("%v", this.Nonce) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringBlockHeader(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *BlockHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBlockHeader
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlockHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlockHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParentHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBlockHeader
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParentHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UncleHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBlockHeader
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UncleHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coinbase", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBlockHeader
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Coinbase = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBlockHeader
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBlockHeader
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiptHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBlockHeader
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceiptHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bloom", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBlockHeader
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bloom = append(m.Bloom[:0], dAtA[iNdEx:postIndex]...)
			if m.Bloom == nil {
				m.Bloom = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Difficulty", wireType)
			}
			m.Difficulty = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Difficulty |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Number", wireType)
			}
			m.Number = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Number |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasLimit", wireType)
			}
			m.GasLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasLimit |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasUsed", wireType)
			}
			m.GasUsed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasUsed |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			m.Time = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Time |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtraData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBlockHeader
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExtraData = append(m.ExtraData[:0], dAtA[iNdEx:postIndex]...)
			if m.ExtraData == nil {
				m.ExtraData = []byte{}
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MixDigest", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBlockHeader
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MixDigest = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlockHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBlockHeader(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBlockHeader
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBlockHeader(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBlockHeader
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBlockHeader
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBlockHeader
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthBlockHeader
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowBlockHeader
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipBlockHeader(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthBlockHeader = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBlockHeader   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("github.com/maichain/eth-indexer/indexer/pb/block_header.proto", fileDescriptorBlockHeader)
}

var fileDescriptorBlockHeader = []byte{
	// 695 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xd4, 0x41, 0x6f, 0xd3, 0x3c,
	0x18, 0x07, 0xf0, 0xa5, 0xeb, 0xba, 0xd5, 0xed, 0xbb, 0xed, 0xcd, 0xbb, 0x77, 0x44, 0x20, 0x25,
	0xc5, 0x5c, 0x2a, 0xb4, 0xad, 0x30, 0x98, 0x10, 0x85, 0x09, 0xa8, 0x8a, 0xb4, 0x09, 0x24, 0x50,
	0x60, 0x37, 0xa4, 0xe2, 0x24, 0x5e, 0x6a, 0x2d, 0x89, 0x43, 0xe2, 0x48, 0x2d, 0x27, 0xbe, 0x01,
	0x57, 0x3e, 0x0e, 0xc7, 0x1d, 0x39, 0x72, 0x8a, 0x58, 0x77, 0xcb, 0x91, 0x4f, 0x80, 0xf2, 0xa4,
	0x5d, 0x62, 0x21, 0xed, 0x54, 0xfb, 0xef, 0xc7, 0x3f, 0xd7, 0xc9, 0xd3, 0xa2, 0x43, 0x97, 0x89,
	0x71, 0x62, 0xed, 0xd9, 0xdc, 0xef, 0xf9, 0x84, 0xd9, 0x63, 0xc2, 0x82, 0x1e, 0x15, 0xe3, 0x5d,
	0x16, 0x38, 0x74, 0x42, 0xa3, 0xde, 0xe2, 0x33, 0xb4, 0x7a, 0x96, 0xc7, 0xed, 0xb3, 0xd1, 0x98,
	0x12, 0x87, 0x46, 0x7b, 0x61, 0xc4, 0x05, 0x57, 0x6b, 0xa1, 0x75, 0x73, 0xb7, 0x42, 0xb8, 0xdc,
	0xe5, 0x3d, 0x58, 0xb2, 0x92, 0x53, 0x98, 0xc1, 0x04, 0x46, 0xc5, 0x16, 0xfc, 0x15, 0xa1, 0xd6,
	0x20, 0x97, 0x8e, 0x00, 0x52, 0x87, 0xa8, 0x76, 0x3c, 0xd4, 0x94, 0x8e, 0xd2, 0xad, 0x0f, 0x1e,
	0x66, 0xa9, 0xd1, 0x66, 0xce, 0x0e, 0xf7, 0x99, 0xa0, 0x7e, 0x28, 0xa6, 0xbf, 0x53, 0xa3, 0xe3,
	0xf2, 0xc8, 0xef, 0xe3, 0x30, 0x62, 0x3e, 0x89, 0xa6, 0xa3, 0x33, 0x3a, 0xc5, 0x1d, 0x87, 0xd2,
	0x90, 0x7e, 0x4a, 0x88, 0xd7, 0xc7, 0xbb, 0xd8, 0xac, 0x1d, 0x0f, 0xd5, 0x8f, 0xa8, 0x15, 0x92,
	0x88, 0x06, 0x62, 0x34, 0x26, 0xf1, 0x58, 0xab, 0x75, 0x94, 0x6e, 0x73, 0xf0, 0x2c, 0x4b, 0x8d,
	0xff, 0x2b, 0xb1, 0xe4, 0xe2, 0xc2, 0xb5, 0xb9, 0x97, 0xf8, 0x41, 0xbf, 0x52, 0xf5, 0x24, 0x66,
	0x9f, 0x69, 0x7f, 0xff, 0xe0, 0x00, 0x9b, 0xa8, 0x88, 0x8f, 0x48, 0x3c, 0x56, 0x3f, 0x20, 0x94,
	0x04, 0xb6, 0x47, 0x8b, 0x03, 0x96, 0xe1, 0x80, 0xc3, 0x2c, 0x35, 0xb6, 0xca, 0x54, 0xf2, 0x6f,
	0x4b, 0x7e, 0x59, 0x54, 0xe1, 0x9b, 0x90, 0x82, 0x7e, 0x82, 0xd6, 0x6c, 0xce, 0x02, 0x8b, 0xc4,
	0x54, 0xab, 0x83, 0xfd, 0x38, 0x4b, 0x0d, 0x75, 0x91, 0x49, 0xb2, 0x21, 0xc9, 0x8b, 0x92, 0x8a,
	0x7b, 0x45, 0xa9, 0x2f, 0x51, 0x3d, 0xe2, 0x5c, 0x68, 0x2b, 0x40, 0xde, 0xcf, 0x52, 0x63, 0x3d,
	0x9f, 0x4b, 0xdc, 0x2d, 0x89, 0xcb, 0x97, 0x2b, 0x14, 0x6c, 0x57, 0xdf, 0xa2, 0x55, 0x31, 0x29,
	0x2e, 0xde, 0x00, 0xe9, 0x51, 0x96, 0x1a, 0xff, 0xce, 0x23, 0x09, 0xd3, 0x25, 0x6c, 0x5e, 0x51,
	0xf1, 0x1a, 0x62, 0x02, 0xf7, 0x75, 0x50, 0x3b, 0xa2, 0x36, 0x65, 0xe1, 0xfc, 0x85, 0xad, 0x02,
	0xfb, 0x22, 0x4b, 0x8d, 0xed, 0x6a, 0x2e, 0xd9, 0x77, 0xe4, 0x2f, 0x5a, 0x29, 0xab, 0x1c, 0xd0,
	0x9a, 0xe7, 0x70, 0xca, 0x73, 0xb4, 0x62, 0x79, 0x9c, 0xfb, 0xda, 0x5a, 0x47, 0xe9, 0xb6, 0x07,
	0x77, 0xb3, 0xd4, 0xd8, 0x80, 0x40, 0x72, 0xff, 0x93, 0x5c, 0x58, 0xc7, 0x66, 0xb1, 0x51, 0x7d,
	0x8f, 0x90, 0xc3, 0x4e, 0x4f, 0x99, 0x9d, 0x78, 0x62, 0xaa, 0x35, 0x3b, 0x4a, 0x77, 0x19, 0xba,
	0x74, 0xab, 0x4c, 0x25, 0x4b, 0x93, 0xac, 0xb2, 0x08, 0x9b, 0x15, 0x47, 0x1d, 0xa2, 0x46, 0x90,
	0xf8, 0x16, 0x8d, 0x34, 0x04, 0xe2, 0x4e, 0x96, 0x1a, 0x9b, 0x45, 0x22, 0x69, 0x5b, 0x92, 0x56,
	0x14, 0x60, 0x73, 0xbe, 0x57, 0x7d, 0x83, 0x9a, 0x2e, 0x89, 0x47, 0x1e, 0xf3, 0x99, 0xd0, 0x5a,
	0xf0, 0x03, 0xda, 0xcf, 0xf2, 0xeb, 0x2c, 0x42, 0xc9, 0xba, 0x21, 0x59, 0x57, 0x35, 0xd8, 0x5c,
	0x73, 0x49, 0xfc, 0x3a, 0x1f, 0xaa, 0xaf, 0x50, 0x3e, 0x1e, 0x25, 0x31, 0x75, 0xb4, 0x36, 0x78,
	0xf7, 0xf2, 0x26, 0x5c, 0x64, 0x12, 0xb7, 0xfd, 0x17, 0x97, 0x97, 0x60, 0x73, 0xd5, 0x25, 0xf1,
	0x49, 0x4c, 0x1d, 0xf5, 0x29, 0xaa, 0x0b, 0xe6, 0x53, 0xed, 0x1f, 0x80, 0xba, 0x79, 0xeb, 0xe5,
	0x73, 0x09, 0x51, 0xe5, 0x6e, 0x61, 0x3e, 0xc5, 0x26, 0xec, 0x52, 0xdf, 0x21, 0x44, 0x27, 0x22,
	0x22, 0x23, 0x87, 0x08, 0xa2, 0xad, 0xc3, 0xeb, 0x83, 0xe7, 0x5e, 0xa6, 0xd7, 0x3c, 0xf7, 0xb2,
	0x08, 0x9b, 0x4d, 0x98, 0x0c, 0x89, 0x20, 0x39, 0xea, 0xb3, 0xc9, 0xc8, 0x61, 0x2e, 0x8d, 0x85,
	0xb6, 0x01, 0x2d, 0x07, 0x68, 0x99, 0x5e, 0x83, 0x96, 0x45, 0xd8, 0x6c, 0xfa, 0x6c, 0x32, 0x84,
	0x71, 0xde, 0x63, 0x01, 0x0f, 0x6c, 0xaa, 0x6d, 0xc2, 0x45, 0xa1, 0xc7, 0x20, 0xb8, 0xa6, 0xc7,
	0x60, 0x1d, 0x9b, 0xc5, 0xc6, 0x41, 0xe7, 0xfc, 0x42, 0x5f, 0xfa, 0x79, 0xa1, 0x2f, 0x7d, 0x99,
	0xe9, 0xca, 0xf9, 0x4c, 0x57, 0x7e, 0xcc, 0x74, 0xe5, 0xd7, 0x4c, 0x57, 0xbe, 0x5d, 0xea, 0x4b,
	0xdf, 0x2f, 0x75, 0xc5, 0x6a, 0xc0, 0x5f, 0xe7, 0x83, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc1,
	0x54, 0x86, 0x54, 0xae, 0x05, 0x00, 0x00,
}
