// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/maichain/eth-indexer/indexer/pb/transaction_receipt.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TransactionReceipt struct {
	ID                uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"id,omitempty" gorm:"primary_key" deepequal:"-"`
	Root              []byte `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty" gorm:"column:root"`
	Status            uint32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty" gorm:"column:status"`
	CumulativeGasUsed uint64 `protobuf:"varint,4,opt,name=cumulative_gas_used,json=cumulativeGasUsed,proto3" json:"cumulative_gas_used,omitempty" gorm:"column:cumulative_gas_used"`
	Bloom             []byte `protobuf:"bytes,5,opt,name=bloom,proto3" json:"bloom,omitempty" gorm:"column:bloom"`
	TxHash            string `protobuf:"bytes,6,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty" gorm:"column:tx_hash;size:255"`
	ContractAddress   string `protobuf:"bytes,7,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty" gorm:"column:contract_address;size:255"`
	GasUsed           uint64 `protobuf:"varint,8,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty" gorm:"column:gas_used"`
}

func (m *TransactionReceipt) Reset()      { *m = TransactionReceipt{} }
func (*TransactionReceipt) ProtoMessage() {}
func (*TransactionReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptorTransactionReceipt, []int{0}
}

func init() {
	proto.RegisterType((*TransactionReceipt)(nil), "pb.TransactionReceipt")
}
func (m *TransactionReceipt) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TransactionReceipt) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTransactionReceipt(dAtA, i, uint64(m.ID))
	}
	if len(m.Root) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTransactionReceipt(dAtA, i, uint64(len(m.Root)))
		i += copy(dAtA[i:], m.Root)
	}
	if m.Status != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintTransactionReceipt(dAtA, i, uint64(m.Status))
	}
	if m.CumulativeGasUsed != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintTransactionReceipt(dAtA, i, uint64(m.CumulativeGasUsed))
	}
	if len(m.Bloom) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintTransactionReceipt(dAtA, i, uint64(len(m.Bloom)))
		i += copy(dAtA[i:], m.Bloom)
	}
	if len(m.TxHash) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintTransactionReceipt(dAtA, i, uint64(len(m.TxHash)))
		i += copy(dAtA[i:], m.TxHash)
	}
	if len(m.ContractAddress) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintTransactionReceipt(dAtA, i, uint64(len(m.ContractAddress)))
		i += copy(dAtA[i:], m.ContractAddress)
	}
	if m.GasUsed != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintTransactionReceipt(dAtA, i, uint64(m.GasUsed))
	}
	return i, nil
}

func encodeVarintTransactionReceipt(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *TransactionReceipt) Size() (n int) {
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovTransactionReceipt(uint64(m.ID))
	}
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovTransactionReceipt(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovTransactionReceipt(uint64(m.Status))
	}
	if m.CumulativeGasUsed != 0 {
		n += 1 + sovTransactionReceipt(uint64(m.CumulativeGasUsed))
	}
	l = len(m.Bloom)
	if l > 0 {
		n += 1 + l + sovTransactionReceipt(uint64(l))
	}
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovTransactionReceipt(uint64(l))
	}
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovTransactionReceipt(uint64(l))
	}
	if m.GasUsed != 0 {
		n += 1 + sovTransactionReceipt(uint64(m.GasUsed))
	}
	return n
}

func sovTransactionReceipt(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozTransactionReceipt(x uint64) (n int) {
	return sovTransactionReceipt(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *TransactionReceipt) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TransactionReceipt{`,
		`ID:` + fmt.Sprintf("%v", this.ID) + `,`,
		`Root:` + fmt.Sprintf("%v", this.Root) + `,`,
		`Status:` + fmt.Sprintf("%v", this.Status) + `,`,
		`CumulativeGasUsed:` + fmt.Sprintf("%v", this.CumulativeGasUsed) + `,`,
		`Bloom:` + fmt.Sprintf("%v", this.Bloom) + `,`,
		`TxHash:` + fmt.Sprintf("%v", this.TxHash) + `,`,
		`ContractAddress:` + fmt.Sprintf("%v", this.ContractAddress) + `,`,
		`GasUsed:` + fmt.Sprintf("%v", this.GasUsed) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringTransactionReceipt(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *TransactionReceipt) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransactionReceipt
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TransactionReceipt: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TransactionReceipt: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransactionReceipt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransactionReceipt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTransactionReceipt
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransactionReceipt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CumulativeGasUsed", wireType)
			}
			m.CumulativeGasUsed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransactionReceipt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CumulativeGasUsed |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bloom", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransactionReceipt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTransactionReceipt
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bloom = append(m.Bloom[:0], dAtA[iNdEx:postIndex]...)
			if m.Bloom == nil {
				m.Bloom = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransactionReceipt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransactionReceipt
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransactionReceipt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransactionReceipt
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasUsed", wireType)
			}
			m.GasUsed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransactionReceipt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasUsed |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTransactionReceipt(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTransactionReceipt
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTransactionReceipt(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTransactionReceipt
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTransactionReceipt
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTransactionReceipt
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthTransactionReceipt
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTransactionReceipt
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTransactionReceipt(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTransactionReceipt = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTransactionReceipt   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("github.com/maichain/eth-indexer/indexer/pb/transaction_receipt.proto", fileDescriptorTransactionReceipt)
}

var fileDescriptorTransactionReceipt = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xbb, 0x21, 0x7f, 0xca, 0xaa, 0xd0, 0x76, 0x8b, 0x90, 0x55, 0x09, 0xdb, 0xec, 0x85,
	0x08, 0x35, 0x0d, 0x02, 0x2a, 0xa4, 0xc0, 0x01, 0x22, 0x0b, 0x88, 0xb8, 0x20, 0x0b, 0xce, 0xd6,
	0xda, 0x5e, 0xec, 0x15, 0xb1, 0xd7, 0xec, 0xae, 0xab, 0x84, 0x13, 0x8f, 0xc1, 0x4b, 0xf0, 0x0e,
	0x1c, 0x7b, 0xe4, 0xc8, 0xc9, 0xa2, 0xe9, 0xcd, 0x47, 0x9e, 0x00, 0x65, 0x9d, 0x92, 0x6e, 0x95,
	0x93, 0x3d, 0xf3, 0xcd, 0xf7, 0x1b, 0xcd, 0x67, 0x43, 0x2f, 0x61, 0x2a, 0x2d, 0xc3, 0xe3, 0x88,
	0x67, 0xc3, 0x8c, 0xb0, 0x28, 0x25, 0x2c, 0x1f, 0x52, 0x95, 0x0e, 0x58, 0x1e, 0xd3, 0x19, 0x15,
	0xc3, 0xcb, 0x67, 0x11, 0x0e, 0x95, 0x20, 0xb9, 0x24, 0x91, 0x62, 0x3c, 0x0f, 0x04, 0x8d, 0x28,
	0x2b, 0xd4, 0x71, 0x21, 0xb8, 0xe2, 0xa8, 0x55, 0x84, 0x87, 0x83, 0x2b, 0xa4, 0x84, 0x27, 0x7c,
	0xa8, 0xa5, 0xb0, 0xfc, 0xa4, 0x2b, 0x5d, 0xe8, 0xb7, 0xc6, 0x82, 0x7f, 0x74, 0x20, 0xfa, 0xb0,
	0x06, 0xfa, 0x0d, 0x0f, 0x79, 0xb0, 0x35, 0xf1, 0x2c, 0xe0, 0x82, 0x7e, 0x7b, 0xfc, 0xb4, 0xae,
	0x9c, 0x1d, 0x16, 0x1f, 0xf1, 0x8c, 0x29, 0x9a, 0x15, 0x6a, 0xfe, 0xb7, 0x72, 0xdc, 0x84, 0x8b,
	0x6c, 0x84, 0x0b, 0xc1, 0x32, 0x22, 0xe6, 0xc1, 0x67, 0x3a, 0xc7, 0x6e, 0x4c, 0x69, 0x41, 0xbf,
	0x94, 0x64, 0x3a, 0xc2, 0x03, 0xec, 0xb7, 0x26, 0x1e, 0x7a, 0x01, 0xdb, 0x82, 0x73, 0x65, 0xb5,
	0x5c, 0xd0, 0xdf, 0x19, 0xf7, 0xeb, 0xca, 0xb9, 0xbd, 0xac, 0x0d, 0x12, 0x6a, 0x48, 0x11, 0x9f,
	0x96, 0x59, 0x3e, 0x5a, 0xca, 0xd8, 0xd7, 0x2e, 0xe4, 0xc1, 0xae, 0x54, 0x44, 0x95, 0xd2, 0xba,
	0xe1, 0x82, 0xfe, 0xad, 0xf1, 0x51, 0x5d, 0x39, 0x7b, 0x4d, 0xc7, 0x20, 0xdc, 0x31, 0x08, 0xcd,
	0x00, 0xf6, 0x57, 0x5e, 0x74, 0x0a, 0x0f, 0xa2, 0x32, 0x2b, 0xa7, 0x44, 0xb1, 0x53, 0x1a, 0x24,
	0x44, 0x06, 0xa5, 0xa4, 0xb1, 0xd5, 0xd6, 0xa7, 0xbd, 0xae, 0x2b, 0xe7, 0xde, 0x06, 0xd9, 0xe0,
	0xdf, 0x37, 0xf8, 0x1b, 0xa6, 0xb1, 0xbf, 0xbf, 0xee, 0xbe, 0x21, 0xf2, 0xa3, 0xa4, 0x31, 0x7a,
	0x09, 0x3b, 0xe1, 0x94, 0xf3, 0xcc, 0xea, 0xe8, 0xe3, 0x1f, 0xd6, 0x95, 0xb3, 0xab, 0x1b, 0x06,
	0xfb, 0xc0, 0x60, 0x6b, 0x1d, 0xfb, 0x8d, 0x11, 0xbd, 0x87, 0x3d, 0x35, 0x0b, 0x52, 0x22, 0x53,
	0xab, 0xeb, 0x82, 0xfe, 0xcd, 0xf1, 0xb3, 0xba, 0x72, 0xf6, 0x57, 0x2d, 0x83, 0x62, 0x1b, 0x94,
	0xd5, 0xc4, 0x73, 0xc9, 0xbe, 0xd2, 0xd1, 0xe3, 0x93, 0x13, 0xec, 0x77, 0xd5, 0xec, 0x2d, 0x91,
	0x29, 0x52, 0x70, 0x2f, 0xe2, 0xb9, 0x12, 0x24, 0x52, 0x01, 0x89, 0x63, 0x41, 0xa5, 0xb4, 0x7a,
	0x1a, 0x3d, 0xa9, 0x2b, 0xe7, 0xf0, 0xba, 0x66, 0xec, 0x78, 0x60, 0xa6, 0x70, 0x6d, 0xf4, 0xca,
	0xb2, 0xdd, 0x4b, 0xed, 0x55, 0x23, 0xa1, 0x77, 0x70, 0xfb, 0x7f, 0xec, 0xdb, 0x3a, 0xf6, 0x47,
	0xf5, 0xf2, 0xbb, 0x6f, 0xca, 0xfa, 0xae, 0xb1, 0x65, 0x1d, 0x70, 0x2f, 0x69, 0x62, 0x1d, 0xbb,
	0x67, 0xe7, 0xf6, 0xd6, 0xef, 0x73, 0x7b, 0xeb, 0xdb, 0xc2, 0x06, 0x67, 0x0b, 0x1b, 0xfc, 0x5a,
	0xd8, 0xe0, 0xcf, 0xc2, 0x06, 0xdf, 0x2f, 0xec, 0xad, 0x9f, 0x17, 0x36, 0x08, 0xbb, 0xfa, 0xc7,
	0x7e, 0xf2, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x76, 0x55, 0x06, 0xb0, 0x53, 0x03, 0x00, 0x00,
}
