// Code generated by mockery v1.0.0
package mocks

import common "github.com/ethereum/go-ethereum/common"
import mock "github.com/stretchr/testify/mock"
import model "github.com/getamis/eth-indexer/model"

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// BatchInsert provides a mock function with given fields: subs
func (_m *Store) BatchInsert(subs []*model.Subscription) ([]common.Address, error) {
	ret := _m.Called(subs)

	var r0 []common.Address
	if rf, ok := ret.Get(0).(func([]*model.Subscription) []common.Address); ok {
		r0 = rf(subs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.Address)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]*model.Subscription) error); ok {
		r1 = rf(subs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BatchUpdateBlockNumber provides a mock function with given fields: blockNumber, addrs
func (_m *Store) BatchUpdateBlockNumber(blockNumber int64, addrs [][]byte) error {
	ret := _m.Called(blockNumber, addrs)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, [][]byte) error); ok {
		r0 = rf(blockNumber, addrs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: blockNumber
func (_m *Store) Find(blockNumber int64) ([]*model.Subscription, error) {
	ret := _m.Called(blockNumber)

	var r0 []*model.Subscription
	if rf, ok := ret.Get(0).(func(int64) []*model.Subscription); ok {
		r0 = rf(blockNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Subscription)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(blockNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByGroup provides a mock function with given fields: groupID, query
func (_m *Store) FindByGroup(groupID int64, query *model.QueryParameters) ([]*model.Subscription, uint64, error) {
	ret := _m.Called(groupID, query)

	var r0 []*model.Subscription
	if rf, ok := ret.Get(0).(func(int64, *model.QueryParameters) []*model.Subscription); ok {
		r0 = rf(groupID, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Subscription)
		}
	}

	var r1 uint64
	if rf, ok := ret.Get(1).(func(int64, *model.QueryParameters) uint64); ok {
		r1 = rf(groupID, query)
	} else {
		r1 = ret.Get(1).(uint64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(int64, *model.QueryParameters) error); ok {
		r2 = rf(groupID, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindOldSubscriptions provides a mock function with given fields: addrs
func (_m *Store) FindOldSubscriptions(addrs [][]byte) ([]*model.Subscription, error) {
	ret := _m.Called(addrs)

	var r0 []*model.Subscription
	if rf, ok := ret.Get(0).(func([][]byte) []*model.Subscription); ok {
		r0 = rf(addrs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Subscription)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([][]byte) error); ok {
		r1 = rf(addrs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTotalBalance provides a mock function with given fields: blockNumber, token, group
func (_m *Store) FindTotalBalance(blockNumber int64, token common.Address, group int64) (*model.TotalBalance, error) {
	ret := _m.Called(blockNumber, token, group)

	var r0 *model.TotalBalance
	if rf, ok := ret.Get(0).(func(int64, common.Address, int64) *model.TotalBalance); ok {
		r0 = rf(blockNumber, token, group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TotalBalance)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64, common.Address, int64) error); ok {
		r1 = rf(blockNumber, token, group)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertTotalBalance provides a mock function with given fields: data
func (_m *Store) InsertTotalBalance(data *model.TotalBalance) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.TotalBalance) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reset provides a mock function with given fields: from, to
func (_m *Store) Reset(from int64, to int64) error {
	ret := _m.Called(from, to)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(from, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
