// Code generated by mockery v1.0.0
package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import pb "github.com/maichain/eth-indexer/service/pb"

// ERC20ServiceServer is an autogenerated mock type for the ERC20ServiceServer type
type ERC20ServiceServer struct {
	mock.Mock
}

// AddERC20 provides a mock function with given fields: _a0, _a1
func (_m *ERC20ServiceServer) AddERC20(_a0 context.Context, _a1 *pb.AddERC20Request) (*pb.AddERC20Response, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pb.AddERC20Response
	if rf, ok := ret.Get(0).(func(context.Context, *pb.AddERC20Request) *pb.AddERC20Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.AddERC20Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.AddERC20Request) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
