// Code generated by mockery v1.0.0
package mocks

import context "context"
import grpc "google.golang.org/grpc"
import mock "github.com/stretchr/testify/mock"
import pb "github.com/getamis/eth-indexer/service/pb"

// ERC20ServiceClient is an autogenerated mock type for the ERC20ServiceClient type
type ERC20ServiceClient struct {
	mock.Mock
}

// AddERC20 provides a mock function with given fields: ctx, in, opts
func (_m *ERC20ServiceClient) AddERC20(ctx context.Context, in *pb.AddERC20Request, opts ...grpc.CallOption) (*pb.AddERC20Response, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *pb.AddERC20Response
	if rf, ok := ret.Get(0).(func(context.Context, *pb.AddERC20Request, ...grpc.CallOption) *pb.AddERC20Response); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.AddERC20Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.AddERC20Request, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
