// Code generated by mockery v1.0.0
package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import model "github.com/getamis/eth-indexer/model"

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, from, to
func (_m *Store) Delete(ctx context.Context, from int64, to int64) error {
	ret := _m.Called(ctx, from, to)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, from, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindTransaction provides a mock function with given fields: ctx, hash
func (_m *Store) FindTransaction(ctx context.Context, hash []byte) (*model.Transaction, error) {
	ret := _m.Called(ctx, hash)

	var r0 *model.Transaction
	if rf, ok := ret.Get(0).(func(context.Context, []byte) *model.Transaction); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTransactionsByBlockHash provides a mock function with given fields: ctx, blockHash
func (_m *Store) FindTransactionsByBlockHash(ctx context.Context, blockHash []byte) ([]*model.Transaction, error) {
	ret := _m.Called(ctx, blockHash)

	var r0 []*model.Transaction
	if rf, ok := ret.Get(0).(func(context.Context, []byte) []*model.Transaction); ok {
		r0 = rf(ctx, blockHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, blockHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ctx, data
func (_m *Store) Insert(ctx context.Context, data *model.Transaction) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Transaction) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
